### ISSUE TITLE
memory is growing until the thread is close :(

### ISSUE THREAD

**Issue by Zeus64** [andremussche/scalemm#24]
i create an application with 10 threads, each thread doing in loop some database queries (and the memory allocation need to handle the response), and after 1 or 2 min i have out of memory :(

if i stop the loop and close all thread before the out of memory error then the memory go down to it's starting level (around 12mb)

**Comment by andremussche** [comment]
can you also reproduce it with a small test application? (with no database
or maybe with sqllite?)
what do you do with the result of the queries: it is processed/used in an
other thread?

2015-11-06 15:15 GMT+01:00 loki5100 notifications@github.com:

**Comment by Zeus64** [comment]
you can see the application here (svn):
https://svn.code.sf.net/p/alcinoe/code/

in the drectory /demo/ALDatabaseBenchmark

it's also work with sqllite3, memcached, mongodb, firebird, mysql, etc.. doesn't really matter, simply launch with loop and select 10 or 20 for "Nb of thread". it's more easy to see the bug if the query return lot of row (around 10 for exemple will be enalf) 

you will need devExpress to compile the demo.

it's was just an application to with i switch fastmm to scalemm, so it's was not really build to test scalemm, but it's show that moving from fastmm to scalemm result with bug :(

**Comment by Zeus64** [comment]
i m soo sorry for the false issue, it's was not connected to scalemm at all :( but it's was connected to my code instead :( sorry !

anyway the good new is that now the application is 5 time (yes 5 times) more faster with scalemm than without (on multithread)

i didn't know, but with fastmm, more processor cores you will have, more slow will be your multithread application !! with fastmm, by setting the processor afinity to only one processor (in the task manager), i succed to have performance close to scalemm on 8 cores. fastmm with 8 cores, it's 5 times more slower than scalemm on 8 cores

**Comment by andremussche** [comment]
thanks for the response anyway :)

About the speed of fastmm on a single processor: can you post some times? Because it is interresting on how fastmm performs unpinned and pinned on a processor for other users and scenarios
So please the times of fastmm unpinned, fastmm pinned, and scalemm?

**Comment by Zeus64** [comment]
Ok, so i didn't use a dedicated application, simply use databaseBenchmark 

https://svn.code.sf.net/p/alcinoe/code/
in the drectory /demo/ALDatabaseBenchmark

who work on multithread to stress a database server. 

0.12ms by query
![ScaleMM2](http://c1.staticflickr.com/1/775/22877719959_acc507603c_b.jpg)

0.15ms by query
![ScaleMM2](http://c2.staticflickr.com/6/5807/22618567753_7cc3182ba7_b.jpg)

0.19ms by query
![ScaleMM2](http://c1.staticflickr.com/1/758/23245690225_32ee3798fd_b.jpg)

0.15ms by query
![ScaleMM2](http://c2.staticflickr.com/6/5677/22949839250_5172c13c1d_b.jpg)

**Comment by andremussche** [comment]
thanks for the screenshots! Did you run the database too on the same
computer?
Because I don't understand the high cpu when running on one core...

CPU affinity to one (!) core makes it single threaded, right?
so that explains the same speed (0.15ms) for both FastMM en SMM when
running on one core.
(so ScaleMM is fast in single threaded mode too, nice! :) )

2015-11-23 16:40 GMT+01:00 loki5100 notifications@github.com:
